@apiBaseUri = http://localhost:2527

### Health Check
GET {{apiBaseUri}}/healthz



### Create Expense
POST {{apiBaseUri}}/expenses
Content-Type: application/json

{
	"title": "buy a new phone",
	"amount": 0.5,
	"note": "",
	"tags": ["gadget", "shopping"]
}

### Create Expense with empty required
POST {{apiBaseUri}}/expenses
Content-Type: application/json

{
	"title": "",
	"amount": 1,
	"note": "",
	"tags": []
}

### Get Expense with Id
GET {{apiBaseUri}}/expenses/1

### Get Expense with unknown Id
GET {{apiBaseUri}}/expenses/54

### Get Expense with strinng
GET {{apiBaseUri}}/expenses/mdsmksl

### Update Expense with Id
PUT {{apiBaseUri}}/expenses/1
Content-Type: application/json

{
	"title": "strawberry cheese cake",
	"amount": 50,
	"note": "",
	"tags": ["food", "cake"]
}