@startuml

title: Get all expenses
actor Client
participant API
database Database 

Client -> API: [GET] /api/expenses
activate API
API -> Database: execute query SQL for expense
activate Database
Database --> API: expense result
deactivate Database
API --> Client: 200 Ok \n Expenses {[{...}]...}
deactivate API

@enduml